Basis-Theory/docs

- source/includes/api-reference/_applications.md
- source/includes/api-reference/_getting_started.md
> Postman button!

- source/includes/api-reference/_authentication.md
- source/includes/elements/_initialize.md
- Updates links in authentication section to point to application section of api reference
> docs: update links in authentication sections

- source/includes/_index_intro.md
- source/includes/api-reference/_getting_started.md
- source/includes/elements/_getting_started.md
> removing waitlist copy

- source/api-reference/index.html.md
- source/elements/index.html.md
- source/includes/api-reference/_errors.md
- source/includes/api-reference/_limits.md
- source/includes/elements/_limits.md
- Showing the rate limits in docs
> Adding limits and rate limit error

- source/includes/api-reference/_getting_started.md
> postman link update

- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- Fix curl examples for create card and bank
> docs: fix curl examples for create card and bank

- source/index.html.md
- updating the Weight of nav links
> fixing weight

- source/includes/api-reference/_tokens.md
> Remove required column

- config.rb
- source/api-reference/index.html.md
- source/elements/index.html.md
- source/index.html.md
> chore: copy cleanup

- source/layouts/layout.erb
- Adds meta tags to page header
> chore: update meta tags

- source/layouts/layout.erb
> chore: updating  og:image

- .github/ISSUE_TEMPLATE.md
- source/api-reference/index.html.md
- source/elements/index.html.md
- source/index.html.md
> ENG-1282 Update discord link

- source/includes/api-reference/_applications.md
- Change name of `public` application type from `Public` to `Client-side Application` to match portal
> chore: ENG-1291 - Update name of 'public' application type to match name shown in portal

- source/includes/api-reference/_tokens.md
- Adds provider field to encryption metadata
> chore: add provider to encryption metadata

- config.rb
- lib/nesting_unique_head.rb
- Replace renderer head to Nesting Unique Head Counter on config.rb to generate HTML `id` for each section
**Prod**
**Fix**
> [ENG-1320] Same link using per multiples titles

- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_errors.md
- Adds documentation for Reactor errors and common scenarios.
> chore: Add documentation for common POST */react errors

- README.md
- makefile
- package.json
- scripts/start.sh
- scripts/stop.sh
- source/includes/api-reference/_applications.md
- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_authentication.md
- source/includes/api-reference/_introduction.md
- source/includes/api-reference/_pagination.md
- source/includes/api-reference/_permissions.md
- source/includes/api-reference/_reactor_formulas.md
- source/includes/api-reference/_reactors.md
- source/includes/api-reference/_tenants.md
- source/includes/api-reference/_token_associations.md
- source/includes/api-reference/_tokens.md
- source/includes/elements/_element_events.md
- source/includes/elements/_elements_instance.md
- source/includes/elements/_initialize.md
- source/includes/elements/_intro.md
- source/includes/elements/_permissions.md
- source/includes/elements/_store_credit_card.md
- After implementation [Same link for multiple items] (https://github.com/slatedocs/slate/wiki/Using-the-same-link-for-several-menu-items) had to be necessary to update interlinks on the content
> [ENG-1363] Update quick links on Api references and Elements

- source/includes/_index_intro.md
- source/includes/elements/_initialize.md
- source/includes/elements/_store_credit_card.md
- Fixing a few small issues with documentation
> updating copy and fixing broken links

- source/includes/_index_intro.md
> fix: create account link

- source/includes/api-reference/_getting_started.md
- source/includes/elements/_getting_started.md
- Opening the `/register` endpoint when redirecting to the Portal for account creation.
> fix: Redirect to /register page for Create an Account

- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_tokens.md
- Adds fingerprint to the card, bank, and token output model docs and sample responses
Example:
> ENG-1403: Adds fingerprint to the card, bank, and token output model docs

- source/includes/api-reference/_applications.md
- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_reactor_formulas.md
- source/includes/api-reference/_reactors.md
- source/includes/api-reference/_tenants.md
- source/includes/api-reference/_tokens.md
- Adding documentation for created_at, created_by, modified_at, modified_by fields
> feat: Adding docs for audit fields

- source/includes/api-reference/_tenants.md
- Adds new property for `monthly_active_tokens` to Tenant Usage Report object
> feat: add monthly_active_tokens to Tenant Usage Report object

- source/includes/api-reference/_tenants.md
- Removes enrichment properties for tenant usage report
> feat: remove enrichment properties from tenant usage report

- source/includes/api-reference/_tenants.md
- Adds included monthly active tokens to tenant usage report
> feat: add included monthly active tokens to tenant usage report

- source/includes/api-reference/_logs.md
- Update Log Object response model with new `actor_id` and `actor_type` properties
- Removes legacy `application` property
> feat: add actor_id and actor_type to log object response

- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_tokens.md
- source/includes/elements/_store_credit_card.md
- Document new React Response object
- Update required permissions for creating an atomic bank and card reaction
- Remove get reaction by ID endpoints
- Fix table formatting
> feat: update react response and required permissions for atomic card and bank react endpoints

- source/elements/index.html.md
- source/includes/elements/_element_mask.md
- source/includes/elements/_elements_instance.md
- adds details about mask for text element
> feat: adds details about mask for text element

- source/includes/elements/_elements_instance.md
Documents new Text Element `placeholder` option for create / update
> ENG-1730 - feat: add text element placeholder option

- source/includes/elements/_elements_instance.md
Document TextElement `aria-label`
> ENG-1728 - feat: add aria-label

- source/api-reference/index.html.md
- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_token_associations.md
- source/includes/api-reference/_tokenize.md
- source/includes/api-reference/_tokens.md
> feat: add tokenize docs, remove billing details, cleanup encryption examples

- source/includes/elements/_elements_services.md
- Adds docs for creating generic tokens with elements
> ENG-1724 - Create generic tokens with elements

- source/elements/index.html.md
- source/includes/elements/_element_mask.md
- source/includes/elements/_element_transform.md
- source/includes/elements/_elements_instance.md
- adds transform attribute for text elements
> feat: adds transform attribute for text elements

- source/includes/elements/_element_mask.md
- adds validation details for mask
> fix: adds validation details for mask

- source/api-reference/index.html.md
- source/includes/api-reference/_applications.md
- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_authentication.md
- source/includes/api-reference/_correlation_id.md
- source/includes/api-reference/_getting_started.md
- source/includes/api-reference/_logs.md
- source/includes/api-reference/_permissions.md
- source/includes/api-reference/_reactor_formulas.md
- source/includes/api-reference/_reactors.md
- source/includes/api-reference/_tenants.md
- source/includes/api-reference/_token_associations.md
- source/includes/api-reference/_tokenize.md
- source/includes/api-reference/_tokens.md
- source/stylesheets/_variables.scss
- source/stylesheets/screen.css.scss
- Adds python SDK documentation
- Change code examples font to `Source Code Pro`
> ENG-1957 - Adds Python SDK documentation

- source/includes/api-reference/_tokens.md
- Adds documentation for new `metadata` query parameter on `GET /tokens`
> feat: add docs for searching tokens by metadata

- source/includes/api-reference/_proxy.md
- source/includes/api-reference/_reactor_formulas.md
- Update beta section headers to remove `-beta` from the anchor
> fix: remove -beta suffix from section anchors

- source/includes/_index_intro.md
> fix: update pii js guide link

- source/includes/api-reference/_logs.md
- Clarifies example values of `entity_type` in Log Object
> fix: update description of entity_type property in Log Object

- source/api-reference/index.html
Redirects user from `api-reference` to index
> ENG-2595 - fix: add replace redirect for api-reference

- source/includes/api-reference/_reactors.md
- source/stylesheets/screen.css.scss
- Update style of beta tags
- Fix link to Use Token Data in Reactors guide
> [ENG-2375] Fixing link to guide; update beta tag styles

- .github/ISSUE_TEMPLATE.md
- source/elements/index.html.md
> chore: update community link

- source/includes/api-reference/_ip_addresses.md
- source/index.html.md
> feat: add static ip addresses

- source/includes/api-reference/_applications.md
- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_logs.md
- source/includes/api-reference/_pagination.md
- source/includes/api-reference/_permissions.md
- source/includes/api-reference/_reactor_formulas.md
- source/includes/api-reference/_reactors.md
- source/includes/api-reference/_tenant_members.md
- source/includes/api-reference/_tenants.md
- source/includes/api-reference/_token_associations.md
- source/includes/api-reference/_tokenize.md
- source/includes/api-reference/_tokens.md
- source/index.html.md
- Adds python sdk code examples for remaining clients
- Removes beta tag from python SDK tab
> feat: add python sdk code examples for all clients

- source/includes/api-reference/_applications.md
- source/includes/api-reference/_getting_started.md
- source/includes/api-reference/_reactor_formulas.md
- source/includes/api-reference/_reactors.md
- source/index.html.md
> feat: adds Go SDK docs

- source/includes/api-reference/_atomic_banks.md
- source/includes/api-reference/_atomic_cards.md
- source/includes/api-reference/_reactor_formulas.md
- source/includes/api-reference/_reactors.md
- Adds a bit more content around private reactor formulas
> feat: Improve docs around private reactor formulas

- source/index.html.md
- Adds link to side navigation for our System Status [page](https://status.basistheory.com/)
> feat: add System Status to side nav

- source/includes/api-reference/_expressions.md
- source/includes/api-reference/_tokenize.md
- source/includes/api-reference/_tokens.md
- source/index.html.md
- Adding docs around search_indexes and liquid filters
> feat: adding json filter docs and clean up

- source/includes/api-reference/_reactor_formulas.md
- Update reactor formula request params section
- [] Not Applicable
> feat: updating reactor formula request params docs

- source/includes/expressions/_filters.md
- add `stringify` custom filter
> feat: adds stringify custom filter

- source/includes/api-reference/_proxy.md
- Documents limitations around headers available within the proxy
> feat: Documenting proxy header limitations

- source/includes/api-reference/_errors.md
- source/includes/api-reference/_logs.md
- source/includes/api-reference/_permissions.md
- source/includes/api-reference/_reactor_formulas.md
- Documents how to catch errors in all sdks
- Documents /logs/entity-types endpoint
- Documents all management permissions
- Fixes some other minor inconsistencies
> feat: fixes inconsistencies in docs

- source/includes/elements/vanilla/_element_options_style.md
- source/stylesheets/_variables.scss
- source/stylesheets/header.css.scss
- source/stylesheets/home.css.scss
- source/stylesheets/screen.css.scss
> feat: update fonts

- source/includes/api-reference/_tokens.md
- Adds documentation around token expiration and `expires_at` property.
> ENG-3162 - Add token TTL docs

- source/includes/api-reference/_tokens.md
- source/includes/elements/vanilla/_element_events.md
- Card last 4 on change event docs
> feat: adding card last 4 change event docs

- source/elements/index.html.md
- source/includes/elements/react/_basis_theory_react.md
- source/includes/elements/vanilla/_element_methods.md
- source/includes/elements/vanilla/_elements_instance.md
- source/includes/elements/vanilla/_tokenization.md
- Adds docs for `focus` and `blur` methods
- Concentrate all elements methods in a new section
> feat: add docs for elements focus and blur

- source/includes/api-reference/_proxy.md
- source/stylesheets/screen.css.scss
Fixes Proxy authentication explanation based on user feedback.
Adds `bt-proxy-key` query param documentation
> fix: explain proxy auth options

- source/includes/expressions/_filters.md
- Adds docs for `to_boolean`, `to_number`, `to_string` filters
> feat: Adds docs for to_boolean, to_number, to_string filters

- source/includes/elements/_intro.md
- Add coming soon message for reveal elements
> feat: add reveal coming soon

- source/includes/api-reference/_applications.md
- source/includes/api-reference/_permissions.md
- Document expiring app type, expires at, can create expiring apps and conditions
> Eng 3756 expiring application docs

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- source/includes/api-reference/_proxy.md
- Updates proxy section of docs
> feat: update proxy section

- source/includes/api-reference/_proxy.md
> feat: fix proxy examples

- source/includes/api-reference/_tokens.md
- Fixes trailing whitespace in token expressions
> fix: add trailing whitespace to token expressions
